AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  EmailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EmailSenderFunction
      Handler: lambda_function.send_email
      Runtime: python3.8
      CodeUri: s3://emailsenderbuck/99739b3e973c3859b6f85118fe2bf5c5
      Environment:
        Variables:
          REGION_NAME: eu-north-1
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ses:SendEmail
          Resource: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /send-email
            Method: POST
    Metadata:
      SamResourceId: EmailSenderFunction
